name: CI pipeline

on: 
  pull_request:
    branches: [main]
  
  push:
    branches: [main]
  

jobs:
  execute: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: setup python
        uses: actions/setup-python@v5.2.0

      - name: run python app
        run: python app.py
